name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build APK with Gradle Build Action
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleDebug
        build-root-directory: .
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: RGB-LED-Controller-Debug
        path: app/build/outputs/apk/debug/app-debug.apk
